# Generated by Django 5.1 on 2024-08-18 12:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cadeira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(blank=True, max_length=100, null=True)),
                ('Email', models.CharField(blank=True, max_length=100, null=True)),
                ('Data_cadastro', models.DateField(blank=True, null=True)),
                ('Data_Nascimento', models.DateField(blank=True, null=True)),
                ('Estado_civil', models.CharField(blank=True, max_length=100, null=True)),
                ('Grupo', models.CharField(blank=True, max_length=100, null=True)),
                ('Situacao_atual', models.CharField(blank=True, max_length=100, null=True)),
                ('observacoes', models.CharField(blank=True, max_length=256, null=True)),
                ('genero', models.CharField(blank=True, max_length=100, null=True)),
                ('celular', models.CharField(blank=True, max_length=20, null=True)),
                ('clinica', models.CharField(blank=True, max_length=100, null=True)),
                ('local_nascimento', models.CharField(blank=True, max_length=100, null=True)),
                ('CPF', models.CharField(blank=True, max_length=100, null=True)),
                ('RG', models.CharField(blank=True, max_length=100, null=True)),
                ('Orgao_emissor', models.CharField(blank=True, max_length=100, null=True)),
                ('Convenio', models.CharField(blank=True, max_length=100, null=True)),
                ('Plano', models.CharField(blank=True, max_length=100, null=True)),
                ('Data_adesao', models.DateField(blank=True, null=True)),
                ('Nome_pai', models.CharField(blank=True, max_length=100, null=True)),
                ('CPF_pai', models.CharField(blank=True, max_length=100, null=True)),
                ('RG_pai', models.CharField(blank=True, max_length=100, null=True)),
                ('Telefone_pai', models.CharField(blank=True, max_length=100, null=True)),
                ('Nome_mae', models.CharField(blank=True, max_length=100, null=True)),
                ('Cpf_mae', models.CharField(blank=True, max_length=100, null=True)),
                ('Rg_mae', models.CharField(blank=True, max_length=100, null=True)),
                ('Telefone_mae', models.CharField(blank=True, max_length=100, null=True)),
                ('CEP', models.IntegerField(blank=True, null=True)),
                ('Endereco', models.CharField(blank=True, max_length=100, null=True)),
                ('Numero', models.IntegerField(blank=True, null=True)),
                ('Complemento', models.CharField(blank=True, max_length=100, null=True)),
                ('Bairro', models.CharField(blank=True, max_length=100, null=True)),
                ('Cidade', models.CharField(blank=True, max_length=100, null=True)),
                ('Estado', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Agendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario', models.DateTimeField()),
                ('duracao', models.IntegerField(blank=True, null=True)),
                ('confirmacao', models.CharField(blank=True, max_length=100, null=True)),
                ('dentista', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('cadeira', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.cadeira')),
                ('paciente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.paciente')),
            ],
        ),
    ]
