# Generated by Django 5.1 on 2024-08-19 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_eventmember'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='paciente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='app.paciente'),
        ),
    ]
