# Generated by Django 5.1 on 2024-08-26 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_anotacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='Bairro',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='CEP',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='CPF',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='Cidade',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='Complemento',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='Convenio',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='Data_Nascimento',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='Data_adesao',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='Data_cadastro',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='Email',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='Endereco',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='Estado',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='Estado_civil',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='Grupo',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='Nome',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='Numero',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='Orgao_emissor',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='Plano',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='RG',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='Situacao_atual',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='celular',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='clinica',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='genero',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='local_nascimento',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='observacoes',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
