# Generated by Django 5.1 on 2024-08-28 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_paciente_bairro_alter_paciente_cep_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Odontograma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dente1', models.TextField()),
                ('dente2', models.TextField()),
                ('dente3', models.TextField()),
                ('dente4', models.TextField()),
                ('dente5', models.TextField()),
                ('dente6', models.TextField()),
                ('dente7', models.TextField()),
                ('dente8', models.TextField()),
                ('dente9', models.TextField()),
                ('dente10', models.TextField()),
                ('dente11', models.TextField()),
                ('dente12', models.TextField()),
                ('dente13', models.TextField()),
                ('dente14', models.TextField()),
                ('dente15', models.TextField()),
                ('dente16', models.TextField()),
                ('dente17', models.TextField()),
                ('dente18', models.TextField()),
                ('dente19', models.TextField()),
                ('dente20', models.TextField()),
                ('dente21', models.TextField()),
                ('dente22', models.TextField()),
                ('dente23', models.TextField()),
                ('dente24', models.TextField()),
                ('dente25', models.TextField()),
                ('dente26', models.TextField()),
                ('dente27', models.TextField()),
                ('dente28', models.TextField()),
                ('dente29', models.TextField()),
                ('dente30', models.TextField()),
                ('dente31', models.TextField()),
                ('dente32', models.TextField()),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='odontograma', to='app.paciente')),
            ],
        ),
    ]
