# Generated by Django 5.1 on 2024-08-28 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_odontograma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='odontograma',
            name='dente1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='odontograma',
            name='dente10',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='odontograma',
            name='dente11',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='odontograma',
            name='dente12',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='odontograma',
            name='dente13',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='odontograma',
            name='dente14',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='odontograma',
            name='dente15',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='odontograma',
            name='dente16',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='odontograma',
            name='dente17',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='odontograma',
            name='dente18',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='odontograma',
            name='dente19',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='odontograma',
            name='dente2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='odontograma',
            name='dente20',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='odontograma',
            name='dente21',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='odontograma',
            name='dente22',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='odontograma',
            name='dente23',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='odontograma',
            name='dente24',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='odontograma',
            name='dente25',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='odontograma',
            name='dente26',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='odontograma',
            name='dente27',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='odontograma',
            name='dente28',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='odontograma',
            name='dente29',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='odontograma',
            name='dente3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='odontograma',
            name='dente30',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='odontograma',
            name='dente31',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='odontograma',
            name='dente32',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='odontograma',
            name='dente4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='odontograma',
            name='dente5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='odontograma',
            name='dente6',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='odontograma',
            name='dente7',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='odontograma',
            name='dente8',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='odontograma',
            name='dente9',
            field=models.TextField(blank=True, null=True),
        ),
    ]
