# Generated by Django 5.1 on 2024-09-10 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_block'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='clicks',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='block',
            name='color',
            field=models.CharField(default='#cccccc', max_length=7),
        ),
        migrations.AlterField(
            model_name='block',
            name='position_x',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='block',
            name='position_y',
            field=models.PositiveIntegerField(),
        ),
    ]
